# Generated by Django 2.0.13 on 2019-10-20 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20161006_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='wbw_list',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='wbw_list',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='wbw_list',
        ),
        migrations.AlterField(
            model_name='bystander',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiebetaaltwat.Participant'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='participants',
            field=models.ManyToManyField(blank=True, to='wiebetaaltwat.Participant'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paymeal', to='wiebetaaltwat.Participant'),
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='Participation',
        ),
        migrations.DeleteModel(
            name='Wbw_list',
        ),
    ]
