language: python
dist: xenial

python:
  - "3.7"

addons:
  apt:
    packages:
      - language-pack-nl

before_install:
  - pip install --upgrade setuptools
  - pip install poetry

install:
  - poetry install
  - poetry add coveralls
script:
  - python manage.py test
  - coverage run --source=orders --omit="*/migrations/*" manage.py test

after_success:
  - coveralls

cache: pip
