language: python
sudo: false

python:
  - "3.6"
  - "3.7"

addons:
  apt:
    packages:
      - language-pack-nl

install:
  - pip install --upgrade pip setuptools
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install coveralls

script:
  - python manage.py test
  - coverage run --source=orders --omit="*/migrations/*" manage.py test

after_success:
  - coveralls

cache: pip
