version: '3.5'
services:
    web:
        build: .
        command: runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        volumes:
            - ./:/usr/src/app/
            - ./db:/usr/src/app/db
            - eetfestijn:/eetfestijn/
        environment:
            DJANGO_DEBUG: 'True'
volumes:
    eetfestijn:
        driver: local
