# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-16 14:14
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor):
    Participant = apps.get_model('wiebetaaltwat', 'Participant')
    Participant.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('wiebetaaltwat', '0002_auto_20161006_0002'),
    ]

    operations = [
        migrations.RunPython(forwards, atomic=True),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wbw_id', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wiebetaaltwat.List'),
            preserve_default=False,
        ),
    ]
