# Generated by Django 2.1b1 on 2018-06-20 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_waterfietsmetkroket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiebetaaltwat.Participant'),
        ),
    ]
