# Generated by Django 2.0.13 on 2019-10-20 19:07

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_new_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='days',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
