name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt install language-pack-nl
        pip install poetry
        pip install coveralls
        poetry install
    - name: Test with Django
      run: |
        poetry run coverage run --source=orders --omit="*/migrations/*" manage.py test

    - name: Upload to Coveralls
      run: |
        COVERALLS_REPO_TOKEN=${{ secrets.github_token }} coveralls
